version: '3.7'

services:
  backend-node:
    container_name: backend_node
    build:
      context: ../backend-node-nest-postgres
      target: development
    volumes:
      - src/backend-node-nest-postgres:/usr/src/backend-node
      - /usr/src/backend-node/node_modules
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    network_mode: "host"
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
